with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  asana_extractor/internal/extractor/port:
    interfaces:
      AsanaClient:
      Writer:
  asana_extractor/internal/config/port:
    interfaces:
      Loader:
