// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "asana_extractor/internal/extractor/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAsanaClient is an autogenerated mock type for the AsanaClient type
type MockAsanaClient struct {
	mock.Mock
}

type MockAsanaClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsanaClient) EXPECT() *MockAsanaClient_Expecter {
	return &MockAsanaClient_Expecter{mock: &_m.Mock}
}

// ListProjects provides a mock function with given fields: ctx, workspaceGID
func (_m *MockAsanaClient) ListProjects(ctx context.Context, workspaceGID string) ([]domain.Project, error) {
	ret := _m.Called(ctx, workspaceGID)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Project, error)); ok {
		return rf(ctx, workspaceGID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Project); ok {
		r0 = rf(ctx, workspaceGID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceGID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAsanaClient_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockAsanaClient_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceGID string
func (_e *MockAsanaClient_Expecter) ListProjects(ctx interface{}, workspaceGID interface{}) *MockAsanaClient_ListProjects_Call {
	return &MockAsanaClient_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx, workspaceGID)}
}

func (_c *MockAsanaClient_ListProjects_Call) Run(run func(ctx context.Context, workspaceGID string)) *MockAsanaClient_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAsanaClient_ListProjects_Call) Return(_a0 []domain.Project, _a1 error) *MockAsanaClient_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAsanaClient_ListProjects_Call) RunAndReturn(run func(context.Context, string) ([]domain.Project, error)) *MockAsanaClient_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, workspaceGID
func (_m *MockAsanaClient) ListUsers(ctx context.Context, workspaceGID string) ([]domain.User, error) {
	ret := _m.Called(ctx, workspaceGID)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return rf(ctx, workspaceGID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = rf(ctx, workspaceGID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceGID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAsanaClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAsanaClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceGID string
func (_e *MockAsanaClient_Expecter) ListUsers(ctx interface{}, workspaceGID interface{}) *MockAsanaClient_ListUsers_Call {
	return &MockAsanaClient_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, workspaceGID)}
}

func (_c *MockAsanaClient_ListUsers_Call) Run(run func(ctx context.Context, workspaceGID string)) *MockAsanaClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAsanaClient_ListUsers_Call) Return(_a0 []domain.User, _a1 error) *MockAsanaClient_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAsanaClient_ListUsers_Call) RunAndReturn(run func(context.Context, string) ([]domain.User, error)) *MockAsanaClient_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAsanaClient creates a new instance of MockAsanaClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsanaClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsanaClient {
	mock := &MockAsanaClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
