// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "asana_extractor/internal/extractor/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// WriteProject provides a mock function with given fields: _a0
func (_m *MockWriter) WriteProject(_a0 domain.Project) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WriteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Project) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_WriteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteProject'
type MockWriter_WriteProject_Call struct {
	*mock.Call
}

// WriteProject is a helper method to define mock.On call
//   - _a0 domain.Project
func (_e *MockWriter_Expecter) WriteProject(_a0 interface{}) *MockWriter_WriteProject_Call {
	return &MockWriter_WriteProject_Call{Call: _e.mock.On("WriteProject", _a0)}
}

func (_c *MockWriter_WriteProject_Call) Run(run func(_a0 domain.Project)) *MockWriter_WriteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Project))
	})
	return _c
}

func (_c *MockWriter_WriteProject_Call) Return(_a0 error) *MockWriter_WriteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_WriteProject_Call) RunAndReturn(run func(domain.Project) error) *MockWriter_WriteProject_Call {
	_c.Call.Return(run)
	return _c
}

// WriteUser provides a mock function with given fields: _a0
func (_m *MockWriter) WriteUser(_a0 domain.User) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WriteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_WriteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteUser'
type MockWriter_WriteUser_Call struct {
	*mock.Call
}

// WriteUser is a helper method to define mock.On call
//   - _a0 domain.User
func (_e *MockWriter_Expecter) WriteUser(_a0 interface{}) *MockWriter_WriteUser_Call {
	return &MockWriter_WriteUser_Call{Call: _e.mock.On("WriteUser", _a0)}
}

func (_c *MockWriter_WriteUser_Call) Run(run func(_a0 domain.User)) *MockWriter_WriteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.User))
	})
	return _c
}

func (_c *MockWriter_WriteUser_Call) Return(_a0 error) *MockWriter_WriteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_WriteUser_Call) RunAndReturn(run func(domain.User) error) *MockWriter_WriteUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
